export const GET_PRODUCTS_LOADING="GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_SUCESS='GET_PRODUCTS_SUCESS'
export const GET_PRODUCTS_ERROR="GET_PRODUCTS_ERROR"



export const GET_SINGLE_PRODUCTS_ERROR="GET_SINGLE_PRODUCTS_ERROR"
export const GET_SINGLE_PRODUCTS_SUCCESS="GET_SINGLE_PRODUCTS_SUCCESS"
export const GET_SINGLE_PRODUCTS_LOADING="GET_SINGLE_PRODUCTS_LOADING"

